- 알고리즘에 처리 하는 것을 처리라고 함
- 알고리즘 전에  데이터를 정제 하는 것을 데이터 전처리라고 한다
- EDA를 통해 데이터의 이상유무,분포를 보고 전처리를 진행한다
- 결측값 처리(Null/NaN)
- 인코딩(문자->숫자), 디코딩(숫자->문자) /// 암호화 인코딩, 풀기 디코딩
- 데이터 스케일링
- 이상치 제거
- feature 선택,추출,가공

## Label encoding
- 전체를 카테고리로 보고, 하나씩 하나의 카테고리를 숫자로 바꾸는 것
- 라벨링해주는 느낌
- 레이블 단위로 바꿀때 많이 사용한다--> 남/여를 바꿀때 좋다 , 카테고리가 많을땐 안좋다

## sklearn.preprocessing.LabelEncoder
- class sklearn.preprocessing.LabelEncoder  --> 선언만, 파라미터 없다
- methonds:
    - fit : Fit label encoder.
    - transform : Transform labels to normalized encoding.
    - fit_transform : Fit label encoder and return encoded labels.

[`fit`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder.fit "sklearn.preprocessing.LabelEncoder.fit")(y)

Fit label encoder.

[`fit_transform`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder.fit_transform "sklearn.preprocessing.LabelEncoder.fit_transform")(y)

Fit label encoder and return encoded labels.

[`get_params`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder.get_params "sklearn.preprocessing.LabelEncoder.get_params")([deep])

Get parameters for this estimator.

[`inverse_transform`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder.inverse_transform "sklearn.preprocessing.LabelEncoder.inverse_transform")(y)

Transform labels back to original encoding.

[`set_output`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder.set_output "sklearn.preprocessing.LabelEncoder.set_output")(*[, transform])

Set output container.

[`set_params`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder.set_params "sklearn.preprocessing.LabelEncoder.set_params")(**params)

Set the parameters of this estimator.

[`transform`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html#sklearn.preprocessing.LabelEncoder.transform "sklearn.preprocessing.LabelEncoder.transform")(y)

Transform labels to normalized encoding.

In [1]:
from sklearn.preprocessing import LabelEncoder
items=['TV','냉장고','전저렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder =LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print("인코딩 변환값:", labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [2]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전저렌지' '컴퓨터']


In [4]:
print('디코딩 원본 값:', encoder.inverse_transform([0, 1, 4, 5, 3, 3, 2, 2]))

디코딩 원본 값: ['TV' '냉장고' '전저렌지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


## 원 - 핫 인코딩
- 1차원 차원을 주고, 1과 0 을 주는 방식
- 치우침이 없다
- feature로 써도 데이터의 특성이 잘 반영이 된다
- 데이터가 스팟하게 바뀌고 오래걸림  -->  오버피팅 문제, 속도가 느려지는 단점이 있다

## sklearn.preprocessing.OneHotEncoder
- class sklearn.preprocessing.OneHotEncoder(*, categories='auto', drop=None, sparse='deprecated', sparse_output=True, dtype=<class 'numpy.float64'>, handle_unknown='error', min_frequency=None, max_categories=None)

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전저렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
encoder =LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
# 2차원 데이터로 변환합니다
labels=labels.reshape(-1,1)

# 원-핫 인코딩을 적용합니다
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코더')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코더
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [6]:
items=['TV','냉장고','전저렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)
print('원-핫 인코더')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

ValueError: Expected 2D array, got 1D array instead:
array=['TV' '냉장고' '전저렌지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.